# Generated by Django 5.0.4 on 2024-05-04 09:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('cnic', models.IntegerField()),
                ('data_of_joining', models.DateField(default=datetime.datetime(2024, 5, 4, 9, 14, 17, 742254, tzinfo=datetime.timezone.utc))),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='EmployeeProfile.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EmployeeProfile.designation')),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeProfile.jobdescription')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmployeeProfile.location'),
        ),
    ]
